name: sport_nest_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  change_app_package_name: ^1.4.0
  cloud_firestore: ^5.4.4
  currency_formatter: ^2.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.0.0
  get: ^4.6.6
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  material_color_gen: ^2.0.0
  material_symbols_icons: ^4.2785.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
